-- MySQL Script generated by MySQL Workbench
-- Thu Jul  7 00:14:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema php_cursalab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema php_cursalab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `php_cursalab` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `php_cursalab` ;

-- -----------------------------------------------------
-- Table `php_cursalab`.`tbl_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_cursalab`.`tbl_profiles` (
  `id_profile` INT NOT NULL AUTO_INCREMENT,
  `pr_name` VARCHAR(30) NOT NULL,
  `pr_state` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_profile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `php_cursalab`.`tbl_persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_cursalab`.`tbl_persons` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `id_profile` INT NOT NULL,
  `p_name` VARCHAR(30) NOT NULL,
  `p_last_name` VARCHAR(70) NOT NULL,
  `p_state` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_person`),
  INDEX `fk_tbl_persons_id_profile_idx` (`id_profile` ASC) ,
  CONSTRAINT `fk_tbl_persons_id_profile`
    FOREIGN KEY (`id_profile`)
    REFERENCES `php_cursalab`.`tbl_profiles` (`id_profile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `php_cursalab`.`tbl_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_cursalab`.`tbl_courses` (
  `id_course` INT NOT NULL AUTO_INCREMENT,
  `id_profile` INT NOT NULL,
  `c_name` VARCHAR(30) NOT NULL,
  `c_description` VARCHAR(70) NOT NULL,
  `c_state` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_course`),
  INDEX `fk_tbl_courses_id_profile_idx` (`id_profile` ASC) ,
  CONSTRAINT `fk_tbl_courses_id_profile`
    FOREIGN KEY (`id_profile`)
    REFERENCES `php_cursalab`.`tbl_profiles` (`id_profile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `php_cursalab`.`tbl_det_per_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_cursalab`.`tbl_det_per_courses` (
  `id_det_per_course` INT NOT NULL AUTO_INCREMENT,
  `id_person` INT NOT NULL,
  `id_course` INT NOT NULL,
  `dpc_date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dpc_date_concluded` DATETIME NULL,
  PRIMARY KEY (`id_det_per_course`),
  INDEX `fk_tbl_det_per_courses_id_person_idx` (`id_person` ASC) ,
  INDEX `fk_tbl_det_per_courses_id_course_idx` (`id_course` ASC) ,
  CONSTRAINT `fk_tbl_det_per_courses_id_person`
    FOREIGN KEY (`id_person`)
    REFERENCES `php_cursalab`.`tbl_persons` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_det_per_courses_id_course`
    FOREIGN KEY (`id_course`)
    REFERENCES `php_cursalab`.`tbl_courses` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `php_cursalab`.`tbl_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_cursalab`.`tbl_topics` (
  `id_topic` INT NOT NULL AUTO_INCREMENT,
  `id_course` INT NOT NULL,
  `t_name` VARCHAR(50) NOT NULL,
  `t_calification` CHAR(2) NOT NULL,
  `t_attempts` CHAR(2) NOT NULL DEFAULT '3',
  `t_state` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_topic`),
  INDEX `fk_tb_topics_id_course_idx` (`id_course` ASC) ,
  CONSTRAINT `fk_tbl_topics_id_course`
    FOREIGN KEY (`id_course`)
    REFERENCES `php_cursalab`.`tbl_courses` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `php_cursalab`.`tbl_det_per_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_cursalab`.`tbl_det_per_topics` (
  `id_det_per_topic` INT NOT NULL AUTO_INCREMENT,
  `id_det_per_course` INT NOT NULL,
  `id_course` INT NOT NULL,
  `id_topic` INT NOT NULL,
  `dp_calification` CHAR(2) NULL,
  `dp_attempts` CHAR(2) NOT NULL,
  `dp_state` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_det_per_topic`),
  INDEX `fk_tbl_id_det_per_topics_id_det_per_course_idx` (`id_det_per_course` ASC) ,
  CONSTRAINT `fk_tbl_det_per_topics_id_det_per_course`
    FOREIGN KEY (`id_det_per_course`)
    REFERENCES `php_cursalab`.`tbl_det_per_courses` (`id_det_per_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `php_cursalab`.`tbl_profiles`
-- -----------------------------------------------------
START TRANSACTION;
USE `php_cursalab`;
INSERT INTO `php_cursalab`.`tbl_profiles` (`id_profile`, `pr_name`, `pr_state`) VALUES (NULL, 'NORMAL', 1);
INSERT INTO `php_cursalab`.`tbl_profiles` (`id_profile`, `pr_name`, `pr_state`) VALUES (NULL, 'PREMIUM', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `php_cursalab`.`tbl_persons`
-- -----------------------------------------------------
START TRANSACTION;
USE `php_cursalab`;
INSERT INTO `php_cursalab`.`tbl_persons` (`id_person`, `id_profile`, `p_name`, `p_last_name`, `p_state`) VALUES (NULL, 1, 'Ricardo Chavez', 'Casanova Leon', 1);
INSERT INTO `php_cursalab`.`tbl_persons` (`id_person`, `id_profile`, `p_name`, `p_last_name`, `p_state`) VALUES (NULL, 1, 'Maria Angeles', 'Villanueva Vargas', 1);
INSERT INTO `php_cursalab`.`tbl_persons` (`id_person`, `id_profile`, `p_name`, `p_last_name`, `p_state`) VALUES (NULL, 2, 'Rosalia Liz', 'Carmine Alba', 1);
INSERT INTO `php_cursalab`.`tbl_persons` (`id_person`, `id_profile`, `p_name`, `p_last_name`, `p_state`) VALUES (NULL, 1, 'Carlos Grav', 'Urbano Casta', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `php_cursalab`.`tbl_courses`
-- -----------------------------------------------------
START TRANSACTION;
USE `php_cursalab`;
INSERT INTO `php_cursalab`.`tbl_courses` (`id_course`, `id_profile`, `c_name`, `c_description`, `c_state`) VALUES (NULL, 1, 'Master Javascript ES6', 'Aprende JS y alcanza el siguiente nivel.', 1);
INSERT INTO `php_cursalab`.`tbl_courses` (`id_course`, `id_profile`, `c_name`, `c_description`, `c_state`) VALUES (NULL, 1, 'Backend con Node JS ', 'Desarrolla App con NodeJS un entorno basado en JS y completa tu stack', 1);
INSERT INTO `php_cursalab`.`tbl_courses` (`id_course`, `id_profile`, `c_name`, `c_description`, `c_state`) VALUES (NULL, 1, 'Curso de React JS - Hook', 'Aprende React JS y crea app reactivas.', 1);
INSERT INTO `php_cursalab`.`tbl_courses` (`id_course`, `id_profile`, `c_name`, `c_description`, `c_state`) VALUES (NULL, 1, 'Curso de Vue JS - Composition ApI', 'Ve al siguiente nivel de Vue3 con Pinia ', 1);
INSERT INTO `php_cursalab`.`tbl_courses` (`id_course`, `id_profile`, `c_name`, `c_description`, `c_state`) VALUES (NULL, 2, 'Aprende GraphQL desde cero', 'Comunica tus apps con GraphQL', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `php_cursalab`.`tbl_det_per_courses`
-- -----------------------------------------------------
START TRANSACTION;
USE `php_cursalab`;
INSERT INTO `php_cursalab`.`tbl_det_per_courses` (`id_det_per_course`, `id_person`, `id_course`, `dpc_date_created`, `dpc_date_concluded`) VALUES (NULL, 1, 1, '2022-07-01 19:20:00', '2022-07-10 19:20:00');
INSERT INTO `php_cursalab`.`tbl_det_per_courses` (`id_det_per_course`, `id_person`, `id_course`, `dpc_date_created`, `dpc_date_concluded`) VALUES (NULL, 1, 2, '2022-07-06 19:20:00', NULL);
INSERT INTO `php_cursalab`.`tbl_det_per_courses` (`id_det_per_course`, `id_person`, `id_course`, `dpc_date_created`, `dpc_date_concluded`) VALUES (NULL, 2, 5, '2022-07-02 19:20:00', '2022-07-05 19:20:00');
INSERT INTO `php_cursalab`.`tbl_det_per_courses` (`id_det_per_course`, `id_person`, `id_course`, `dpc_date_created`, `dpc_date_concluded`) VALUES (NULL, 2, 4, '2022-07-10 19:20:00', '2022-07-12 19:20:00');
INSERT INTO `php_cursalab`.`tbl_det_per_courses` (`id_det_per_course`, `id_person`, `id_course`, `dpc_date_created`, `dpc_date_concluded`) VALUES (NULL, 3, 3, '2022-07-15 19:20:00', '2022-07-20 19:20:00');
INSERT INTO `php_cursalab`.`tbl_det_per_courses` (`id_det_per_course`, `id_person`, `id_course`, `dpc_date_created`, `dpc_date_concluded`) VALUES (NULL, 4, 4, '2022-07-06 19:20:00', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `php_cursalab`.`tbl_topics`
-- -----------------------------------------------------
START TRANSACTION;
USE `php_cursalab`;
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 1, 'Introduccion a JS.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 1, 'Fundamentos de JS.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 1, 'Mi primer Script en JS.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 1, 'JS en el Navegador.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 2, 'Introduccion a Node JS.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 2, 'Fundamentos de Node JS.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 2, 'Mipremir script en Node JS.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 3, 'Introduccion a ReactJS.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 3, 'Fundamentos de ReactJS.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 3, 'Mi primer componente en ReactJS.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 3, 'React JS y PreactJS.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 4, 'Introduccion a VueJS.', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 4, 'Options Api y Composition Api', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 5, 'Introduccion a GraphQL', '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_topics` (`id_topic`, `id_course`, `t_name`, `t_calification`, `t_attempts`, `t_state`) VALUES (NULL, 5, 'Configuracion con Apollo y Apollo Client', '20', '3', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `php_cursalab`.`tbl_det_per_topics`
-- -----------------------------------------------------
START TRANSACTION;
USE `php_cursalab`;
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 1, 1, 1, '13', '3', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 1, 1, 2, '18', '2', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 1, 1, 3, '10', '0', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 1, 1, 4, '12', '2', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 2, 2, 5, '19', '3', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 2, 2, 6, '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 2, 2, 7, NULL, '0', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 3, 5, 14, '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 3, 5, 15, '12', '2', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 4, 4, 12, '10', '1', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 4, 4, 13, '15', '2', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 5, 3, 8, '12', '1', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 5, 3, 9, '11', '2', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 5, 3, 10, '17', '3', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 5, 3, 11, '18', '3', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 6, 4, 12, '20', '3', 1);
INSERT INTO `php_cursalab`.`tbl_det_per_topics` (`id_det_per_topic`, `id_det_per_course`, `id_course`, `id_topic`, `dp_calification`, `dp_attempts`, `dp_state`) VALUES (NULL, 6, 4, 13, NULL, '3', 1);

COMMIT;

